apiVersion: v1
kind: ServiceAccount
metadata:
  name: edenfield-sa

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: edenfield-role
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log", "services", "configmaps"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: edenfield-rb
subjects:
  - kind: ServiceAccount
    name: edenfield-sa
roleRef:
  kind: Role
  name: edenfield-role
  apiGroup: rbac.authorization.k8s.io
