apiVersion: v1
kind: Service
metadata:
  name: edenfield-svc
spec:
  selector:
    app: edenfield
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
    - protocol: TCP
      port: 9321
      targetPort: 9321
  type: ClusterIP
